kind: Pod
apiVersion: v1
metadata:
  name: azuredisk-2
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  containers:
  - image: alpine
    name: azuredisk
    command:
    - "/bin/sh"
    - "-c"
    - while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
    volumeMounts:
    - name: azuredisk01
      mountPath: "/mnt/azuredisk"
  volumes:
  - name: azuredisk01
    persistentVolumeClaim:
      claimName: pvc-azuredisk-2
