kind: Pod
apiVersion: v1
metadata:
  name: pod-restored
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  containers:
  - image: alpine
    name: pod-restored
    args:
    - sleep
    - "3600"
    volumeMounts:
    - name: azuredisk01
      mountPath: "/mnt/azuredisk"
  volumes:
  - name: azuredisk01
    persistentVolumeClaim:
      claimName: pvc-azuredisk-snapshot-restored
